package com.gj.weidusore.core.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gj.weidusore.bean.UserInfoLogin;

import com.gj.weidusore.core.db.UserInfoLoginDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoLoginDaoConfig;

    private final UserInfoLoginDao userInfoLoginDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoLoginDaoConfig = daoConfigMap.get(UserInfoLoginDao.class).clone();
        userInfoLoginDaoConfig.initIdentityScope(type);

        userInfoLoginDao = new UserInfoLoginDao(userInfoLoginDaoConfig, this);

        registerDao(UserInfoLogin.class, userInfoLoginDao);
    }
    
    public void clear() {
        userInfoLoginDaoConfig.clearIdentityScope();
    }

    public UserInfoLoginDao getUserInfoLoginDao() {
        return userInfoLoginDao;
    }

}
