package com.gj.weidusore.core.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gj.weidusore.bean.UserInfoLogin;
import com.gj.weidusore.bean.car.ShopCar;

import com.gj.weidusore.core.db.UserInfoLoginDao;
import com.gj.weidusore.core.db.ShopCarDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoLoginDaoConfig;
    private final DaoConfig shopCarDaoConfig;

    private final UserInfoLoginDao userInfoLoginDao;
    private final ShopCarDao shopCarDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoLoginDaoConfig = daoConfigMap.get(UserInfoLoginDao.class).clone();
        userInfoLoginDaoConfig.initIdentityScope(type);

        shopCarDaoConfig = daoConfigMap.get(ShopCarDao.class).clone();
        shopCarDaoConfig.initIdentityScope(type);

        userInfoLoginDao = new UserInfoLoginDao(userInfoLoginDaoConfig, this);
        shopCarDao = new ShopCarDao(shopCarDaoConfig, this);

        registerDao(UserInfoLogin.class, userInfoLoginDao);
        registerDao(ShopCar.class, shopCarDao);
    }
    
    public void clear() {
        userInfoLoginDaoConfig.clearIdentityScope();
        shopCarDaoConfig.clearIdentityScope();
    }

    public UserInfoLoginDao getUserInfoLoginDao() {
        return userInfoLoginDao;
    }

    public ShopCarDao getShopCarDao() {
        return shopCarDao;
    }

}
